# GoReleaser configuration for JIF
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy
    - go run testdata/generate_test_gifs.go
    - go test ./...

builds:
  - id: jif
    main: ./cmd/jif
    binary: jif
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: freebsd
        goarch: arm
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
    flags:
      - -trimpath

archives:
  - id: jif-archive
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance Improvements"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Documentation"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: "Other Changes"
      order: 999

release:
  github:
    owner: Gaurav-Gosain
    name: jif
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## JIF {{ .Tag }} Release

    A modern, high-performance GIF viewer for your terminal.

    ### Installation

    #### Manual Download

    Download the appropriate binary for your platform below, extract it, and run:

    ```bash
    tar xzf jif_*.tar.gz
    ./jif animation.gif
    ```

    #### Go Install

    ```bash
    go install github.com/Gaurav-Gosain/jif/cmd/jif@{{ .Tag }}
    ```

    #### Quick Install Script (Linux/macOS)

    ```bash
    curl -sSL https://raw.githubusercontent.com/Gaurav-Gosain/jif/main/install.sh | bash
    ```
  footer: |
    ---

    **Full Changelog**: https://github.com/Gaurav-Gosain/jif/compare/{{ .PreviousTag }}...{{ .Tag }}

# AUR (Arch User Repository)
# Disabled until AUR_SSH_KEY is configured
# aurs:
#   - name: jif-bin
#     homepage: https://github.com/Gaurav-Gosain/jif
#     description: "A modern, high-performance GIF viewer for your terminal with halfblock rendering"
#     maintainers:
#       - "Gaurav Gosain <itsgauravgosain@gmail.com>"
#     license: MIT
#     private_key: "{{ .Env.AUR_SSH_KEY }}"
#     git_url: "ssh://aur@aur.archlinux.org/jif-bin.git"
#     package: |
#       # bin
#       install -Dm755 "./jif" "${pkgdir}/usr/bin/jif"
#
#       # license
#       install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
#
#       # documentation
#       install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/${pkgname}/README.md"

# Homebrew tap
# Disabled until HOMEBREW_TAP_GITHUB_TOKEN is configured and homebrew-tap repo is created
# homebrew_casks:
#   - name: jif
#     ids:
#       - jif-archive
#     repository:
#       owner: Gaurav-Gosain
#       name: homebrew-tap
#       token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
#     homepage: https://github.com/Gaurav-Gosain/jif
#     description: "A modern, high-performance GIF viewer for your terminal"
#     commit_author:
#       name: goreleaserbot
#       email: bot@goreleaser.com
#     commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"
