name: Feature Request
description: Suggest a new feature or enhancement for JIF.
title: "[FEATURE]: "
labels: ["enhancement"]
assignees: ["Gaurav-Gosain"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature!

        Before submitting, please:
        - Check if a similar feature has already been requested.
        - Review [FUTURE_FEATURES.md](https://github.com/Gaurav-Gosain/jif/blob/main/FUTURE_FEATURES.md) for planned features.
        - Describe the feature clearly and explain why it would be useful.

  - type: input
    id: feature-summary
    attributes:
      label: Feature Summary
      description: A brief one-line summary of the feature.
      placeholder: ex. Add zoom controls for GIF viewing
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: Describe the problem this feature would solve.
      placeholder: ex. Currently, there's no way to zoom in/out on GIF details
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working.
      placeholder: |
        ex. Add keyboard shortcuts:
        - + to zoom in
        - - to zoom out
        - 0 to reset zoom
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: ex. Could also use mouse wheel for zooming
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples.
      placeholder: Drag and drop images here or paste them directly.
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Essential for my use case
      default: 0
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in implementing this feature?
      options:
        - label: I would be willing to submit a PR for this feature
          required: false
